name: Generate Blog Index

on:
  push:
    paths:
      - 'blog/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate blog_index.json
        run: |
          find blog -name '*.html' > blog_files.txt
          node generate_blog_index.js blog_files.txt blog/blog_index.json

      - name: Commit blog_index.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add blog/blog_index.json
          git commit -m "Update blog_index.json" || echo "No changes to commit"
          git push
